### ISSUE TITLE
Unable to compile using AIRFacebook-ANE

### ISSUE THREAD

**Issue by appearance** [marpies/AIRFacebook-ANE#1]
I have followed your guide to add AIRFacebook.ane, support and cardview anes. I am using AIR SDK 23 and followed your guide to replace adt.jar and runtimeClasses.jar from air sdk patch available on your repo. I am getting "already added: Landroid/support/annotation/ColorRes;" error and "java.lang.OutOfMemoryError: Java heap space" error at so many java.util.Arrays methods and other dx classes.
Please help me how can I successfully use your facebook ane. 

Note: I am using Animate CC 2015.2 with AIR SDK 23 (also tried with AIR SDK 24)
on Windows 10 64 bit PC.

**Comment by marpies** [comment]
Are you also using AccountKit ANE? You do not need to patch the SDK if you are using only AIRFacebook.

Show me the list of ANEs that you are including in your app.

**Comment by appearance** [comment]
Apart from your anes, I am using my own ANE which includes android-support-v13.jar. Is this causing the problem? If yes, how can I solve it?

**Comment by marpies** [comment]
I need to know exactly what ANEs you're using, even if they're mine.

android-support-v13 library shouldn't cause a problem.

**Comment by appearance** [comment]
You misunderstood my reply. I said I am using following ANEs:
1. TWShare.ane
2. com.marpies.ane.facebook.ane

That's it.  You know TWShare.ane? This ANE was created by me, myself. I have used android-support-v13.jar in it. I included android-support-v13.jar while building the ANE. 

I rebuilt my TWShare.ane by removing android-support-v13.jar from it as it's included in your facebook.ane, then it compiled without any error. Thank you for this reply. 

Can you tell me how can I provide EventListeners to AIRFacebook.init() function if I am writing my action script code in conventional timeline method. I am not using ActionScript classes.

Thank you.

**Comment by marpies** [comment]
Android-support-v13.jar is not included in com.marpies.ane.facebook.ane. Android-support-v4.jar is included in com.marpies.ane.androidsupport.ane. If you need v13 then use that but do not include my support ANE.

You said you replaced your adt.jar and runtimeclasses.jar but it's only required for AccountKit ANE. You should use default AIR SDK files with this Facebook ANE.

If you're not using classes then use the traditional event system:

```as3
AIRFacebook.addEventListener( AIRFacebookCachedAccessTokenEvent.RESULT, onCachedAccessTokenResult );
AIRFacebook.addEventListener( AIRFacebookBasicUserProfileEvent.PROFILE_READY, onBasicUserProfileReady );
AIRFacebook.addEventListener( AIRFacebookEvent.SDK_INIT, onFacebookSDKInit );

AIRFacebook.init( ... );

function onFacebookSDKInit( event:AIRFacebookEvent ):void {
    AIRFacebook.removeEventListener( AIRFacebookEvent.SDK_INIT, onFacebookSDKInit );
}

function onCachedAccessTokenResult( event:AIRFacebookCachedAccessTokenEvent ):void {
    AIRFacebook.removeEventListener( AIRFacebookCachedAccessTokenEvent.RESULT, onCachedAccessTokenResult );
}

function onBasicUserProfileReady( event:AIRFacebookBasicUserProfileEvent ):void {
    AIRFacebook.removeEventListener( AIRFacebookBasicUserProfileEvent.PROFILE_READY, onBasicUserProfileReady );
    trace( event.basicUserProfile );
}
```

**Comment by appearance** [comment]
You are right. facebook.ane has android-supportv4.jar. TWShare.ane was bundled with android-support.v13 and this in-turn contains v4 also. So, it worked if I remove support-v13.jar from TWShare.ane.

Yes, I didn't repace adt.jar and runtimeclasses.jar after you replied to the first question. 

And thanks a lot for traditional code method example.
