### ISSUE TITLE
AIR 24, Invoke Handler Issue

### ISSUE THREAD

**Issue by dnikolaev** [marpies/AIRFacebook-ANE#3]
Hi Marcel,

I'm adding support for [Android App Links](https://helpx.adobe.com/flash-player/release-note/fp_24_air_24_release_notes.html). 

But there is a conflict with Facebook ANE. 

```
[trace] [VK] onInvoke openUrl args: https://www.flirtymania.com,android.intent.action.VIEW
[trace] [AIRFacebook] onInvoke openUrl
[Fault] exception, information=Error: Error #2101: The String passed to URLVariables.decode() must be a URL-encoded query string containing name/value pairs.
```

<img width="1398" alt="facebook-invoke-handler-issue" src="https://cloud.githubusercontent.com/assets/5558855/22691291/d2655ab6-ed4a-11e6-891f-51afcc9523ce.png">

If you have time please fix it. We won't able to release update until it.

Regards,
Dmitrii

**Comment by marpies** [comment]
Hi @dnikolaev,

Thanks for reporting, I'll have a look at it soon.

**Comment by dnikolaev** [comment]
Fixed at AIRFacebook_1.4.5
