### ISSUE TITLE
Facebook 1.5.0 and Android Support 25.2.0 are not compatible with Android 4.x

### ISSUE THREAD

**Issue by dnikolaev** [marpies/AIRFacebook-ANE#5]
It doesn't work on Android 4.x devices. No crash logs, nothing. 

So I have to use Facebook 1.4.5 and Android Support 24.0.0

**Comment by marpies** [comment]
Hi @dnikolaev,

What AIR version are you using?

**Comment by dnikolaev** [comment]
AIR 25

**Comment by dnikolaev** [comment]
Did you find the problem?

**Comment by marpies** [comment]
It's strange issue and I'm not sure what's causing it. It happened to me on Android 6 as well but now it's working again, even on Android 4. I'll have to investigate a little more.

**Comment by dnikolaev** [comment]
Definitely there is a problem with Android 4.* and Android Support 25.2.0 I'll attach logs from the device.

**Comment by dnikolaev** [comment]
<img width="1128" alt="android-4 3-support-25 2 0-1" src="https://cloud.githubusercontent.com/assets/5558855/26728018/808a900a-47b1-11e7-8fc2-352e1ad5abeb.png">
<img width="1133" alt="android-4 3-support-25 2 0-2" src="https://cloud.githubusercontent.com/assets/5558855/26728024/84f2a8a8-47b1-11e7-88cc-83214f8f279b.png">
<img width="1158" alt="android-4 3-support-25 2 0-3" src="https://cloud.githubusercontent.com/assets/5558855/26728028/8838b0f2-47b1-11e7-881d-afcf105e05bc.png">
<img width="949" alt="android-4 3-support-25 2 0-4" src="https://cloud.githubusercontent.com/assets/5558855/26728031/8bf24096-47b1-11e7-913b-75ac38603327.png">

**Comment by dnikolaev** [comment]
There is a problem with [AccountKit](https://github.com/marpies/account-kit-ane/issues/5) too.

**Comment by dnikolaev** [comment]
There is the same problem with @marchbold [GoogleIdentity ANE](https://github.com/distriqt/ANE-GoogleIdentity/issues/25). We have to collaborate our efforts to resolve this issue.

**Comment by dnikolaev** [comment]
AIR 25.0.0.134
Android 4.3, 4.2.2
Android Support 25.2.0

If I backward to Android Support 24.0.0 (with AIRFacebook_1.4.5) all is ok with Android 4.*
If I use Android > 4.* all is ok.

**Comment by marpies** [comment]
Did you check the number of method references after you create APK with Android support 25.2? Maybe it puts you over the 64K method limit which may be a problem on Android 4 where it is not natively supported. Could you try packaging it with AIR 24 just to check?

I can't reproduce it with my sample project where AIRFacebook v1.5.0 and AccountKit v1.3.0 is packaged together. I can login just fine on Android 4.4 and Android Support 25.2.0. There must be something else going on.

**Comment by dnikolaev** [comment]
I'm not hitting the 64k function limit. According to [APK method count](http://inloop.github.io/apk-method-count/) – 49251 (multidex enabled).

It looks like I've found the solution. If I compile with AIR 24.0.0.180, ANEs will work perfect. According to [APK method count](http://inloop.github.io/apk-method-count/) – 48542. So AIR 25.0.0.134 (multidex enabled) with Android Support 25.2.0 are not compatible with Android 4.3, 4.2.2

**Comment by dnikolaev** [comment]
[Multidex support prior to Android 5.0](https://developer.android.com/studio/build/multidex.html)

In order to get around this limitation, you can use the [multidex support library](https://developer.android.com/topic/libraries/support-library/packages.html#multidex).

I'll be glad if you package [multidex support library](https://developer.android.com/topic/libraries/support-library/packages.html#multidex) like additional [Android dependency ANEs](https://github.com/marpies/android-dependency-anes). I'm looking forward to your reply.

**Comment by marpies** [comment]
Ok thanks for the report.

**Comment by dnikolaev** [comment]
I've just found the solution for this bug.

You need to change the manifest additions for the application tag to match the following and use the MultiDexApplication:
```
<manifest android:installLocation="auto">
	<!-- PERMISSIONS -->

	<application android:name="android.support.multidex.MultiDexApplication">

		<!-- ACTIVITIES / RECEIVERS / SERVICES -->

	</application>
</manifest>
```
