### ISSUE TITLE
Don't work in OS 10 / IPhone 5

### ISSUE THREAD

**Issue by tufik2** [marpies/AIRFacebook-ANE#6]
Hi, when I try to call  AIRFacebook.loginWithReadPermissions(this.permissions, this); the app close instantly.

Air 25
IPhone 5
OS 10

**Comment by marpies** [comment]
Hi,

Did you follow the [setup guide](http://marpies.com/2015/09/setup-adobe-air-with-facebook), specifically the section about adding the necessary information to your InfoAddtions? Having the XML descriptor incomplete is a common reason for a crash when trying to log in on iOS.
