### ISSUE TITLE
i taken this message.

### ISSUE THREAD

**Issue by orcuncun** [marpies/AIRFacebook-ANE#9]
D:\CALISMALARINTUMU\androidoyunlarimiz\ANEDENEMELERİ\facedenemesi-Marpies\ana.as, Line 21, Column 74	1067: Implicit coercion of a value of type ana to an unrelated type com.marpies.ane.facebook.listeners:IAIRFacebookLoginListener.

**Comment by marpies** [comment]
Implement the interface `IAIRFacebookLoginListener` on your `ana` class and it will work.
